version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: user-service-postgres
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  kafka:
    image: bitnami/kafka:latest
    container_name: user-service-kafka
    environment:
      - KAFKA_CREATE_TOPICS="users:1:1,auth:1:1"
      - KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami
    depends_on:
      - zookeeper
      - postgres

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: user-service-zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

volumes:
  postgres-data:
  kafka_data:
